# -*- coding: utf-8 -*-
"""Prueba 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fdxh0GczPQhDSr0_UiVkvnNpEhPpN8N3
"""

#ejercicio 1

estudiantes = []


def validar_nombre(nombre):

  return nombre.strip() != ""

def validar_edad(edad):

  return edad > 0

def validar_nota(nota):

  return nota > 0 and nota > 1.0 and nota < 7.0

def leer_opcion():

  while True:

    try:

      opcion = int(input("Ingrese una opción(1-6): "))

      if opcion >= 1 and opcion <= 6:

        return opcion



      else:

        print("Opción inválida. Intente nuevamente.")

    except ValueError:

      print("Opción inválida. Intente nuevamente.")


def agregar_estudiante(lista):

  nombre = input("Ingrese el nombre del estudiante: ")

  if not validar_nombre(nombre):

    print("ERROR. El nombre no puede estár vacío")
    return

  try:

    edad = int(input("Ingrese la edad del estudiante: "))

    if not validar_edad(edad):

      print("ERROR. La edad debe ser mayor a 0")

      return


  except ValueError:

    print("ERROR. La edad debe ser un número entero")
    return

  try:

    nota = float(input("Ingrese la nota del estudiante (decimal entre 1.0 y 7.0): "))

    if not validar_nota(nota):

      print("ERROR. La edad debe ser mayor a 0 y estar entre 1.0 y 7.0")
      return
  except ValueError:

    print("ERROR. La nota debe ser un número decimal")



  estudiante = {"nombre": nombre, "edad": edad, "nota": nota, "aprobado" : False}

  lista.append(estudiantes)

  print("Estudiante agregado con éxito")


def buscar_estudiante(lista, nombre):

  for i in range(len(lista)):

    if nombre == lista[i]["nombre"] == nombre:

      return i1
    

  return -1

def eliminar_estudiante(lista, indice):

  nombre = input("Ingrese el nombre del estudiante a eliminar: ")

  posicion = buscar_estudiante(lista, nombre)

  if posicion != -1:

    lista.pop(posicion)
    print("Estudiante eliminado con éxito")

  else:

    print(f"ERROR. El estudiante {nombre} no existe")

def aprovacion(estudiante):

  nota = estudiante["nota"]

  if nota >= 4.0:

    aprobado = True

  else:

    aprobado = False

def actualizar_estado(lista):

  for estudiante in lista:

    aprovacion(estudiante)


  print("Estado de estudiantes actualizado con éxito")

def mostrar_estudiantes(lista):

  actualizar_estado(lista)

  if len(lista) == 0:

    print("No hay estudiantes registrados")
    return
  print("===LISTA DE ESTUDIANTES===")

  for estudiante in lista:

    aprobado = "Aprobado" if estudiante["aprobado"] else "Desaprovado"

    print(f"Nombre: {estudiante["nombre"]}")
    print(f"Edad: {estudiante["edad"]}")
    print(f"Nota: {estudiante["nota"]}")
    print(f"Estado: {aprobado}")
    print("---------------------------------")

def mostrar_menu():

  print("===MENÚ PRINCIPAL===")

  print("1. Agregar Estudiante")

  print("2. Buscar estudiante")

  print("3. Eliminar estudiante")

  print("4. Actualizar estados")

  print("5. Mostrar estudiantes")

  print("6. Salir")

while True:

  mostrar_menu()

  opcion = leer_opcion()

  if opcion == 1:
    agregar_estudiante(estudiantes)


  elif opcion == 2:

    nombre = input("Ingrese el nombre del estudiante a buscar: ")

    posicion = buscar_estudiante(estudiantes, nombre)

    if posicion != -1:

      est = estudiantes[posicion]

      print("Estudiante encontrado:")

      print("Posicion: ", posicion)

      print("Nombre: ", est["nombre"])

      print("Edad: ", est["edad"])

      print("Nota: ", est["nota"])

      print("Aprobado: ", "Aprobado" if est["aprobado"] else "Desaprobado")

    else:

      print(f"ERROR. El estudiante {nombre} no existe")

  elif opcion == 3:

    eliminar_estudiante(estudiantes)

  elif opcion == 4:

    actualizar_estado(estudiantes)

  elif opcion == 5:

    mostrar_estudiantes(estudiantes)

  elif opcion == 6:

    print("Gracias por usar el sistema. Vuelva Pronto")

    break

  else:

    print("Opción inválida. Intente nuevamente.")